# Generated by Django 5.1.2 on 2024-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=10, max_digits=10000),
        ),
    ]
