# Generated by Django 5.1.2 on 2024-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=10, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=10, max_digits=10000),
        ),
    ]
